V 93187 fix
mitre/microsoft-windows-server-2019-stig-baseline pull request #72
Opened 2021-10-25 19:43 UTC by aagiardd

2021-11-08 16:45 UTC, karikarshivani commented
One edge case to include: If the input 'ntp_servers' has no value set, maybe we can provide a simple output/ skip statement. The error I currently see is this

> ×  ntpserver example at (pry):103 (Got an error when generating description from matcher: TypeError: can't convert Inspec::Input::NO_VALUE_SET to Array (Inspec::Input::NO_VALUE_SET#to_ary gives Inspec::Input::NO_VALUE_SET) -- /opt/inspec/embedded/lib/ruby/gems/2.6.0/gems/rspec-expectations-3.9.2/lib/rspec/matchers/english_phrasing.rb:28:in `Array')
>      can't convert Inspec::Input::NO_VALUE_SET to Array (Inspec::Input::NO_VALUE_SET#to_ary gives Inspec::Input::NO_VALUE_SET)

Thoughts? @aaronlippold @aagiardd

2021-11-08 16:46 UTC, karikarshivani requested changes

2021-11-08 16:46 UTC, karikarshivani commented on test/cookbooks/Win2019STIG/kitchen.vagrant.yml
> +>>>>>>> fb9ed3c8b101522bf393942e085680545636e08a
Looks like there's a conflict that needs to be resolved

2021-11-08 16:46 UTC, karikarshivani commented on controls/V-92963.rb
> +  #if domain_role == '4' || domain_role == '5'
Not sure why this is commented out. The if statement ensures that the test is skipped if the target is not a domain controller (as indicated in the [check text](https://github.com/mitre/microsoft-windows-server-2019-stig-baseline/blob/master/controls/V-92963.rb#L16))

2021-11-08 19:14 UTC, aaronlippold commented
It also looks like the kitchen files got messed up in this pr as well so this needs to be fixed

2021-11-16 18:25 UTC, karikarshivani commented on test/cookbooks/Win2019STIG/kitchen.vagrant.yml
> +>>>>>>> fb9ed3c8b101522bf393942e085680545636e08a
Since the conflict has been resolved, I'll resolve the conversation. Thanks!

2021-11-16 18:27 UTC, karikarshivani commented on controls/V-92963.rb
> -# encoding: UTF-8
Looks like cookstyle did it again @aagiardd

2021-11-16 18:27 UTC, karikarshivani commented on controls/V-92963.rb
> +  #if domain_role == '4' || domain_role == '5'
Thanks for uncommenting this condition. Resolving conversation.

2021-11-18 17:42 UTC, karikarshivani commented on controls/V-92963.rb
> -# encoding: UTF-8
Resolving this since it was addressed

2021-11-30 18:14 UTC, karikarshivani commented
Hey @aagiardd 
Could you send me an email with your availability for this week and/or next week? Here's my email:
<img width="205" alt="Screen Shot 2021-11-30 at 1 14 10 PM" src="https://user-images.githubusercontent.com/11844975/144104272-706bb12a-eaf7-41ef-a603-a038e8a54602.png">

2021-12-17 16:25 UTC, merged